### ISSUE TITLE
MTTF (mean time to failure calculations)

### ISSUE THREAD

**Issue by samrudh** [MatthewReid854/reliability#18]
Is the functionality of calculating mean time to fail (MTTF) available?
I intend to work towards the same if that is not available

**Comment by MatthewReid854** [comment]
Mean time to failure is identical to the mean of a distribution.
You can obtain the mean from a distribution object using ".mean"
For example "Weibull_Distribution(alpha=50,beta=2).mean"
In addition to the mean there are many other properties you can access, as detailed here:
https://reliability.readthedocs.io/en/latest/Creating%20and%20plotting%20distributions.html

Please do not use GitHub issues to ask questions on how to use the library. Issues are for bugs or enhancements.
Questions on how to use the library are welcome via email to alpha.reliability@gmail.com as detailed here: https://reliability.readthedocs.io/en/latest/How%20to%20get%20help.html
