### ISSUE TITLE
[BUG] - Quite different results to lifelines with real data

### ISSUE THREAD

**Issue by derrynknife** [MatthewReid854/reliability#21]
**Describe the bug**
Using the "Canadian Senators" data from lifelines, and removing the 0 values, the results from reliability are a bit different to those of lifelines. It is worth investigating:

**To Reproduce**
``` python
import lifelines
from lifelines.datasets import *
from reliability.Fitters import *

df = load_canadian_senators()
x = df['diff_days'].values
c = 1 - df['observed'].astype(int)
zero_idx = (x == 0)
x = x[~zero_idx]
c = c[~zero_idx]

# Failed/suspended format
f = x[c == 0]
s = x[c == 1]

rel_model = Fit_Exponential_1P(f, s, print_results=False, show_probability_plot=False)
print("Rate:")
print(rel_model.Lambda)
ef = lifelines.ExponentialFitter()
ll_lambda = 1./ef.fit(x, 1 - c).params_.values[0]
print(ll_lambda)
print("Life:")
print(1./rel_model.Lambda)
print(1./ll_lambda)
```

**Expected behavior**
I would expect the results to be closer to the lifelines results. I came across this error testing my own package, `SurPyval`, against `reliability` and `lifelines`. `SurPyval` consistently achieves the same results as lifelines, and of all three packages lifelines is the most mature and most popular. Therefore it is the standard so results should probably match it.

**Comment by MatthewReid854** [comment]
When I run this I get:
Rate:
0.0001768661898361167
0.00017686620121539135
Life:
5653.991873328615
5653.991509560265

To me this seems like the answers agree.
What result do you get?

**Comment by derrynknife** [comment]
On an M1 Mac, running OS11.4
```
Rate:
0.00020351687428579846
0.00017686620121539135
Life:
4913.597476913395
5653.991509560265
```

**Comment by derrynknife** [comment]
<img width="782" alt="Screen Shot 2021-08-09 at 7 27 32 pm" src="https://user-images.githubusercontent.com/18457108/128685658-3297a7c8-3867-40a5-b7d6-99581d8266ee.png">

**Comment by MatthewReid854** [comment]
I'm running this on Windows 10.
I thought I might try it on Google Colab (which I believe is a Linux machine) and I got the same result.
![image](https://user-images.githubusercontent.com/35417895/128688713-4beb462d-23b2-418c-a740-70e084c9f8db.png)

Can you please use "pip list" to confirm the version of scipy and reliability that you are using.
I am using scipy 1.7.0 and reliability 0.6.0

If our package versions match then I find it quite interesting that the difference could be caused by the operating system.

**Comment by MatthewReid854** [comment]
I have determined that you must be using an older version of reliability in which the default optimizer was L-BFGS-B. The default was changed to TNC in version 0.6.0. If I force the optimizer to be L-BFGS-B then I get the same result you are getting.

You can either upgrade reliability and repeat the test, or specify optimizer='TNC' in the fitter and the results should match.
If you always want the best optimizer then specify optimizer = 'best'. This is new in 0.6.0 so you'll need to upgrade to try it.

Please confirm if you get the same results on a Mac once you do the above things.

FYI, here's what we're actually fitting
![image](https://user-images.githubusercontent.com/35417895/128697202-e8b2a795-9cb9-43bd-9726-3a8602ea60cd.png)

**Comment by derrynknife** [comment]
Upgrading scipy on M1 is more difficult than one would imagine....

After updating to 0.6.0 this is no longer an issue.

Thanks
