### ISSUE TITLE
MCF Parametric graph feature addition like legends and titles on axis

### ISSUE THREAD

**Issue by Lakshminarayananlak** [MatthewReid854/reliability#26]
Hi , thanks the development of the package . we use the package for study where we need to change the axis legends from time to Kilometer since our data is life estimation over Kilometer. 

also we are trying to integrate  with the streamlit application, can you please provide the code for MCF calculation to plot graph. 
 can you please provide the raw data into a storable object.

**Comment by MatthewReid854** [comment]
The plot title and axes labels can [easily be changed](https://www.python-graph-gallery.com/4-add-title-and-axis-label) using matplotlib commands.

While I have not used Streamlit before, a quick search of [their documentation](https://docs.streamlit.io/library/api-reference/charts/st.line_chart) shows that you can build a plot using arrays of data assembled into a pandas dataframe. The arrays you will need are part of the existing MCF output. Please read the [API reference](https://reliability.readthedocs.io/en/latest/API/Repairable_systems/MCF_nonparametric.html) for details of the outputs.

Here is an example of how you can extract the raw data to reproduce the plot. You will need to do some post processing to make this into a step plot as I have done for the MCF plot.

```
from reliability.Repairable_systems import MCF_nonparametric
import matplotlib.pyplot as plt

times = [
    [5, 10, 15, 17],
    [6, 13, 17, 19],
    [12, 20, 25, 26],
    [13, 15, 24],
    [16, 22, 25, 28],
]
out = MCF_nonparametric(data=times)
x = out.time
y = out.MCF
plt.scatter(x, y, color="k", marker="x")
plt.xlabel("Kilometers")
plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/35417895/148669582-2f9965bd-293f-41c0-b1f5-9084e8490c0f.png)

I'm closing this issue as your request is already possible using a few extra steps. If you have further questions, please contact me [via email](https://reliability.readthedocs.io/en/latest/How%20to%20get%20help.html).
