### ISSUE TITLE
Missing capability to fit Weibull with fixed Beta or Alpha (known Beta or Alpha)

### ISSUE THREAD

**Issue by besunmoon** [MatthewReid854/reliability#3]

**Comment by MatthewReid854** [comment]
Functionality exists for known Beta and is used extensively in ALT_fitters. In Fit_Weibull_2P and Fit_Gamma_2P use force_beta to specify beta as a known value. Similarly use force_sigma for Fit_Lognormal_2P and Fit_Normal_2P. There is no practical application to find beta for a known alpha.
