### ISSUE TITLE
[BUG] - AttributeError: 'Line2D' object has no property 'ci_y'

### ISSUE THREAD

**Issue by Aravinviju** [MatthewReid854/reliability#35]
**Describe the bug**
Hi 
First of all, thanks for creating this intuitive package for Reliability!
I'm trying out the sample codes you've given under each topic in the package, getting a few errors in some parts, one those is below,
In the Package Doc - "see how the confidence bounds on time or reliability should be used based on what we are trying to predict" - "EXAMPLE 1"

**To Reproduce**
`from reliability.Distributions import Weibull_Distribution
from reliability.Fitters import Fit_Weibull_2P
import matplotlib.pyplot as plt

dist = Weibull_Distribution(alpha=500,beta=3)
data = dist.random_samples(10,seed=1)
fit = Fit_Weibull_2P(failures=data,show_probability_plot=False,print_results=False)

plt.figure(figsize=(10,7))
plt.subplot(121)
arrow_x = 25
arrow_y = 0.025

X_lower,X_point,X_upper = fit.distribution.CDF(CI_type='time',CI_y=0.7)
plt.arrow(x=0,y=0.7,dx=X_upper,dy=0,color='red',head_width=arrow_y,head_length=arrow_x,length_includes_head=True)
plt.arrow(x=X_lower,y=0.7,dx=0,dy=-0.7,color='red',head_width=arrow_x,head_length=arrow_y,length_includes_head=True)
plt.arrow(x=X_point,y=0.7,dx=0,dy=-0.7,color='red',head_width=arrow_x,head_length=arrow_y,length_includes_head=True)
plt.arrow(x=X_upper,y=0.7,dx=0,dy=-0.7,color='red',head_width=arrow_x,head_length=arrow_y,length_includes_head=True)
plt.xlim(0,dist.quantile(0.99))
plt.ylim(0,1.1)
plt.text(x=0,y=0.705,s='CI_y=0.7',va='bottom')
plt.text(x=X_lower,y=0.035,s='lower',va='bottom',ha='right',rotation=90)
plt.text(x=X_point,y=0.035,s='point',va='bottom',ha='right',rotation=90)
plt.text(x=X_upper,y=0.035,s='upper',va='bottom',ha='right',rotation=90)
plt.title('Weibull CDF\nConfidence bounds on time')`

The output that Python gave you - 

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-48-c289b8b68c5a> in <module>
     12 arrow_y = 0.025
     13 
---> 14 X_lower,X_point,X_upper = fit.distribution.CDF(CI_type='time',CI_y=0.7)
     15 plt.arrow(x=0,y=0.7,dx=X_upper,dy=0,color='red',head_width=arrow_y,head_length=arrow_x,length_includes_head=True)
     16 plt.arrow(x=X_lower,y=0.7,dx=0,dy=-0.7,color='red',head_width=arrow_x,head_length=arrow_y,length_includes_head=True)

~\Anaconda3\envs\reliability_00\lib\site-packages\reliability\Distributions.py in CDF(self, xvals, xmin, xmax, show_plot, **kwargs)
    479             limits = get_axes_limits()  # get the previous axes limits
    480 
--> 481             p = plt.plot(X, cdf, **kwargs)
    482             plt.xlabel("x values")
    483             plt.ylabel("Fraction failing")

~\Anaconda3\envs\reliability_00\lib\site-packages\matplotlib\pyplot.py in plot(scalex, scaley, data, *args, **kwargs)
   2840     return gca().plot(
   2841         *args, scalex=scalex, scaley=scaley,
-> 2842         **({"data": data} if data is not None else {}), **kwargs)
   2843 
   2844 

~\Anaconda3\envs\reliability_00\lib\site-packages\matplotlib\axes\_axes.py in plot(self, scalex, scaley, data, *args, **kwargs)
   1741         """
   1742         kwargs = cbook.normalize_kwargs(kwargs, mlines.Line2D)
-> 1743         lines = [*self._get_lines(*args, data=data, **kwargs)]
   1744         for line in lines:
   1745             self.add_line(line)

~\Anaconda3\envs\reliability_00\lib\site-packages\matplotlib\axes\_base.py in __call__(self, data, *args, **kwargs)
    271                 this += args[0],
    272                 args = args[1:]
--> 273             yield from self._plot_args(this, kwargs)
    274 
    275     def get_next_color(self):

~\Anaconda3\envs\reliability_00\lib\site-packages\matplotlib\axes\_base.py in _plot_args(self, tup, kwargs)
    417             raise ValueError(f"x has {ncx} columns but y has {ncy} columns")
    418         return [func(x[:, j % ncx], y[:, j % ncy], kw, kwargs)
--> 419                 for j in range(max(ncx, ncy))]
    420 
    421 

~\Anaconda3\envs\reliability_00\lib\site-packages\matplotlib\axes\_base.py in <listcomp>(.0)
    417             raise ValueError(f"x has {ncx} columns but y has {ncy} columns")
    418         return [func(x[:, j % ncx], y[:, j % ncy], kw, kwargs)
--> 419                 for j in range(max(ncx, ncy))]
    420 
    421 

~\Anaconda3\envs\reliability_00\lib\site-packages\matplotlib\axes\_base.py in _makeline(self, x, y, kw, kwargs)
    310         default_dict = self._getdefaults(set(), kw)
    311         self._setdefaults(default_dict, kw)
--> 312         seg = mlines.Line2D(x, y, **kw)
    313         return seg
    314 

~\Anaconda3\envs\reliability_00\lib\site-packages\matplotlib\lines.py in __init__(self, xdata, ydata, linewidth, linestyle, color, marker, markersize, markeredgewidth, markeredgecolor, markerfacecolor, markerfacecoloralt, fillstyle, antialiased, dash_capstyle, solid_capstyle, dash_joinstyle, solid_joinstyle, pickradius, drawstyle, markevery, **kwargs)
    388         # update kwargs before updating data to give the caller a
    389         # chance to init axes (and hence unit support)
--> 390         self.update(kwargs)
    391         self.pickradius = pickradius
    392         self.ind_offset = 0

~\Anaconda3\envs\reliability_00\lib\site-packages\matplotlib\artist.py in update(self, props)
    994                     func = getattr(self, f"set_{k}", None)
    995                     if not callable(func):
--> 996                         raise AttributeError(f"{type(self).__name__!r} object "
    997                                              f"has no property {k!r}")
    998                     ret.append(func(v))

AttributeError: 'Line2D' object has no property 'ci_y'`

**Expected behavior**
was expecting the first graph in the results which is below

**Screenshots**
![image](https://user-images.githubusercontent.com/33582877/226607774-a7eee8eb-c78a-46b9-9db4-46d0a6a18bce.png)

**Additional context**
there are also multiple other errors which I came across similar to this one, I thought its because of the matplotlib may be, the version or something, searched around, there wasn't any solution and then found this to clarify. I can post those other issues too as separate ones later.

**Comment by MatthewReid854** [comment]
I have no problem running this. I suspect that you are not using the most recent version. Please update reliability to 0.8.8 and try again. Let me know if you still encounter the same error once reliability is updated.

**Comment by Aravinviju** [comment]
> 0.8.8

I checked this earlier, the version which was in my env was 0.5.7 ,  I tried upgrading using the upgrade command before and it didn't change from this version, it said its already satisfied.
Now I tried again specifying 0.8.8 and it says it cannot find?

![image](https://user-images.githubusercontent.com/33582877/227174507-9f509fc8-ff35-4951-8b41-f2f35aef8952.png)

**Comment by MatthewReid854** [comment]
Try to use pip so you can get it from [PyPI](https://pypi.org/project/reliability/).
I'm closing this issue and the other similar one because it is clearly an issue with your old version.
If you need to ask more questions about version upgrading, please contact me via email (alpha.reliability@gmail.com).
