### ISSUE TITLE
[BUG] - AttributeError: 'Line2D' object has no property 'quantiles'

### ISSUE THREAD

**Issue by Aravinviju** [MatthewReid854/reliability#36]
**Describe the bug**
Hi
Trying out the "weibull dist fit 2P - quantile specifications - finding the confidence bounds for the quantiles(Y values)" from the package

**To Reproduce**
`from reliability.Distributions import Weibull_Distribution
from reliability.Fitters import Fit_Weibull_2P
from reliability.Other_functions import crosshairs
import matplotlib.pyplot as plt

dist = Weibull_Distribution(alpha=500, beta=6)
data = dist.random_samples(50, seed=1)  # generate some data
# this will produce the large table of quantiles below the first table of results
Fit_Weibull_2P(failures=data, quantiles=True, CI=0.8, show_probability_plot=False)
print('----------------------------------------------------------')
# repeat the process but using specified quantiles.
output = Fit_Weibull_2P(failures=data, quantiles=[0.05, 0.5, 0.95], CI=0.8)
# these points have been manually annotated on the plot using crosshairs
crosshairs()
plt.show()

# the values from the quantiles dataframe can be extracted using pandas:
lower_estimates = output.quantiles['Lower Estimate'].values
print('Lower estimates:', lower_estimates)

#alternatively, the bounds can be extracted from the distribution object
lower,point,upper = output.distribution.CDF(CI_y=[0.05, 0.5, 0.95], CI=0.8)
print('Upper estimates:', upper)`

The output that Python gave you. -

`Results from Fit_Weibull_2P (80% CI):
Analysis method: Maximum Likelihood Estimation (MLE)
Failures / Right censored: 50/0 (0% right censored) 

Parameter  Point Estimate  Standard Error  Lower CI  Upper CI
    Alpha         489.117         13.9217   471.597   507.288
     Beta         5.20799         0.58927   4.50501   6.02067 

Goodness of fit    Value
 Log-likelihood -301.658
           AICc  607.571
            BIC   611.14
             AD 0.482678 

----------------------------------------------------------
Results from Fit_Weibull_2P (80% CI):
Analysis method: Maximum Likelihood Estimation (MLE)
Failures / Right censored: 50/0 (0% right censored) 

Parameter  Point Estimate  Standard Error  Lower CI  Upper CI
    Alpha         489.117         13.9217   471.597   507.288
     Beta         5.20799         0.58927   4.50501   6.02067 

Goodness of fit    Value
 Log-likelihood -301.658
           AICc  607.571
            BIC   611.14
             AD 0.482678 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-17413325f906> in <module>
     10 print('----------------------------------------------------------')
     11 # repeat the process but using specified quantiles.
---> 12 output = Fit_Weibull_2P(failures=data, quantiles=[0.05, 0.5, 0.95], CI=0.8)
     13 # these points have been manually annotated on the plot using crosshairs
     14 crosshairs()

~\Anaconda3\envs\reliability_00\lib\site-packages\reliability\Fitters.py in __init__(self, failures, right_censored, show_probability_plot, print_results, CI, percentiles, CI_type, method, optimizer, force_beta, **kwargs)
   1794                 CI=CI,
   1795                 CI_type=CI_type,
-> 1796                 **kwargs,
   1797             )
   1798             self.probability_plot = plt.gca()

~\Anaconda3\envs\reliability_00\lib\site-packages\reliability\Probability_plotting.py in Weibull_probability_plot(failures, right_censored, fit_gamma, __fitted_dist_params, a, CI, CI_type, show_fitted_distribution, show_scatter_points, **kwargs)
    361     plt.gcf().set_size_inches(9, 9)
    362     if show_fitted_distribution is True:
--> 363         wbf.CDF(label=label, **kwargs)
    364         plt.legend(loc="upper left")
    365     plt.title("Probability plot\nWeibull CDF")

~\Anaconda3\envs\reliability_00\lib\site-packages\reliability\Distributions.py in CDF(self, xvals, xmin, xmax, show_plot, **kwargs)
    479             limits = get_axes_limits()  # get the previous axes limits
    480 
--> 481             p = plt.plot(X, cdf, **kwargs)
    482             plt.xlabel("x values")
    483             plt.ylabel("Fraction failing")

~\Anaconda3\envs\reliability_00\lib\site-packages\matplotlib\pyplot.py in plot(scalex, scaley, data, *args, **kwargs)
   2840     return gca().plot(
   2841         *args, scalex=scalex, scaley=scaley,
-> 2842         **({"data": data} if data is not None else {}), **kwargs)
   2843 
   2844 

~\Anaconda3\envs\reliability_00\lib\site-packages\matplotlib\axes\_axes.py in plot(self, scalex, scaley, data, *args, **kwargs)
   1741         """
   1742         kwargs = cbook.normalize_kwargs(kwargs, mlines.Line2D)
-> 1743         lines = [*self._get_lines(*args, data=data, **kwargs)]
   1744         for line in lines:
   1745             self.add_line(line)

~\Anaconda3\envs\reliability_00\lib\site-packages\matplotlib\axes\_base.py in __call__(self, data, *args, **kwargs)
    271                 this += args[0],
    272                 args = args[1:]
--> 273             yield from self._plot_args(this, kwargs)
    274 
    275     def get_next_color(self):

~\Anaconda3\envs\reliability_00\lib\site-packages\matplotlib\axes\_base.py in _plot_args(self, tup, kwargs)
    417             raise ValueError(f"x has {ncx} columns but y has {ncy} columns")
    418         return [func(x[:, j % ncx], y[:, j % ncy], kw, kwargs)
--> 419                 for j in range(max(ncx, ncy))]
    420 
    421 

~\Anaconda3\envs\reliability_00\lib\site-packages\matplotlib\axes\_base.py in <listcomp>(.0)
    417             raise ValueError(f"x has {ncx} columns but y has {ncy} columns")
    418         return [func(x[:, j % ncx], y[:, j % ncy], kw, kwargs)
--> 419                 for j in range(max(ncx, ncy))]
    420 
    421 

~\Anaconda3\envs\reliability_00\lib\site-packages\matplotlib\axes\_base.py in _makeline(self, x, y, kw, kwargs)
    310         default_dict = self._getdefaults(set(), kw)
    311         self._setdefaults(default_dict, kw)
--> 312         seg = mlines.Line2D(x, y, **kw)
    313         return seg
    314 

~\Anaconda3\envs\reliability_00\lib\site-packages\matplotlib\lines.py in __init__(self, xdata, ydata, linewidth, linestyle, color, marker, markersize, markeredgewidth, markeredgecolor, markerfacecolor, markerfacecoloralt, fillstyle, antialiased, dash_capstyle, solid_capstyle, dash_joinstyle, solid_joinstyle, pickradius, drawstyle, markevery, **kwargs)
    388         # update kwargs before updating data to give the caller a
    389         # chance to init axes (and hence unit support)
--> 390         self.update(kwargs)
    391         self.pickradius = pickradius
    392         self.ind_offset = 0

~\Anaconda3\envs\reliability_00\lib\site-packages\matplotlib\artist.py in update(self, props)
    994                     func = getattr(self, f"set_{k}", None)
    995                     if not callable(func):
--> 996                         raise AttributeError(f"{type(self).__name__!r} object "
    997                                              f"has no property {k!r}")
    998                     ret.append(func(v))

AttributeError: 'Line2D' object has no property 'quantiles'`

![image](https://user-images.githubusercontent.com/33582877/226612076-205eca79-5ddd-4cca-93b3-bf5ee802946b.png)

**Expected behavior**
expected to reproduce whatever results you've given in that section of the package Doc.

**Comment by MatthewReid854** [comment]
I have no problem running this. I suspect that you are not using the most recent version. Please update reliability to 0.8.8 and try again. Let me know if you still encounter the same error once reliability is updated.
