### ISSUE TITLE
BUG about accelerated life experiment module

### ISSUE THREAD

**Issue by nnnnwinder** [MatthewReid854/reliability#37]
**Describe the bug**
Most of the code running the accelerated life experiment module will fail, for example numpy will not use round

**To Reproduce**
from reliability.ALT_fitters import Fit_Weibull_Power
from reliability.Datasets import ALT_load2
import matplotlib.pyplot as plt

Fit_Weibull_Power(failures=ALT_load2().failures, failure_stress=ALT_load2().failure_stresses, 
                  right_censored=ALT_load2().right_censored, right_censored_stress=ALT_load2().right_censored_stresses, 
                  use_level_stress=60)
plt.show()

**Expected behavior**
Output the fit parameters and two graphs, as shown in the example in the documentation

**Screenshots**
![image](https://user-images.githubusercontent.com/87553470/232407103-2c055cd9-0b11-4620-a393-a4f869f40028.png)

**Additional context**
Similar problems exist with functions related to accelerated life experiments

**Comment by nnnnwinder** [comment]
None of the sample code related to the accelerated life experiment in your documentation tutorial seems to work and will report errors.  Look forward to your reply

**Comment by MatthewReid854** [comment]
What version of numpy are you using? The current version is 1.24.2
What version of reliability are you using? The current version is 0.8.8
If either of those are out of date, then try updating them and see if the error persists.
When I run the above "to reproduce" code, I don't get any errors.

**Comment by nnnnwinder** [comment]
Hello
I have checked the relevant package versions required for the reliability package and they are all up to date and compliant
I tried to find out why and found that 'inputs.stresses_for_groups' is a tuple array.  This may be the reason why round cannot be used on arrays.  I looked at the source code, and you used round for the array, so an error is reported
![image](https://user-images.githubusercontent.com/87553470/233363552-a800c685-2b55-413d-828b-c9481af7916a.png)



I'm surprised you're running without errors

**Comment by nnnnwinder** [comment]
##This is the running code for the screenshot above
from reliability.Utils import ALT_fitters_input_checking
from reliability.Other_functions import make_ALT_data
ALT_data = make_ALT_data(distribution='Exponential',life_stress_model='Eyring',a=1500,c=-10,
                         stress_1=[500,400,350],number_of_samples=100,fraction_censored=0.2,seed=1,
                         use_level_stress=use_level_stress)
inputs = ALT_fitters_input_checking(
            dist="Weibull",
            life_stress_model="Power",
            failures=ALT_data.failures,
            failure_stress_1=ALT_data.failure_stresses,
            right_censored=ALT_data.right_censored,
            right_censored_stress_1=ALT_data.right_censored_stresses,
            CI=0.95,
            use_level_stress=60,
            optimizer='TNC',
        )
inputs.stresses_for_groups

------------------------
I still report mistakes.  I feel very distressed.  Looking forward to your reply

**Comment by nnnnwinder** [comment]
My python version is 3.8.5

**Comment by nnnnwinder** [comment]
My output is [(500.0,), (400.0,), (350.0,)], so I get an error, my package version is (numpy == 1.24.2 and reliability ==0.8.8), my python version is 3.8.5, This may be the reason.  I will try to update the software and reply to you.  Thank you very much

**Comment by MatthewReid854** [comment]
Keep your python version at 3.8.5 please. I have updated my python version to 3.11.3 and now I get the same errors. The errors also occurred in Github actions (hence the build and test failing) for 3.9.16. There must have been some update to multiple python versions that affected a few things to cause the same error across multiple python versions.
Now that I get the same error I can troubleshoot it and fix it. Give me a few days as it's a lot of errors to fix. Thanks for identifying this. Leave the issue open until I update reliability.

**Comment by nnnnwinder** [comment]
Ok, thank you very much and look forward to your repair

**Comment by MatthewReid854** [comment]
I have managed to fix this. Please download v0.8.9. See changelog for details. Thanks again for raising this issue.
