### ISSUE TITLE
[BUG] - float128 and complex256

### ISSUE THREAD

**Issue by Filston37** [MatthewReid854/reliability#39]
I am running the library on Windows 10 (and 11) and I get an attribute error when I import the library (both on float128 and complex256. Is there a workaround for this? (other than changing the code in the library)
Thanks

**Comment by CamDavidsonPilon** [comment]
Possibly related to https://github.com/HIPS/autograd/issues/601?

**Comment by MatthewReid854** [comment]
Yes, this was autograd related and looks like they have fixed it in 1.6.2.
Thanks @CamDavidsonPilon for identifying the source of this bug so quickly.
