### ISSUE TITLE
Is Numerical Integration method available  for stress-strength interference? 

### ISSUE THREAD

**Issue by hzyrc6011** [MatthewReid854/reliability#4]
In the tutorial there was only monte-carlo method to simulate the result:
[tutorial link](https://reliability.readthedocs.io/en/latest/Stress-Strength%20interference%20for%20any%20distributions.html)
However monte-carlo method might be slow , and the result may not be accurate.  So I am wondering if numerical intergration method is available. Thanks for your help!

**Comment by TEFEdotCC** [comment]
It seems not to difficult to replace the **Monte-Carlo integration** with another method.
By the way, the **Monte-Carlo integration** is also an numerical integration method like all others ;)

If all distributions under "reliability/Distributions.py" become an method to get the pdf and cdf like the scipy.stats api, there are a simple way to implement the feature.
I had it figured out and start an implementation under #5

**Comment by MatthewReid854** [comment]
If you want the Stress-Strength interference between two Normal distributions, this is available as an exact formula.
Anything other than two normal distributions is currently calculated using Monte-Carlo as it was simple to implement, computes relatively fast, and is reasonably accurate. How many decimal places of accuracy do you really need here?
