### ISSUE TITLE
RankAdjustment

### ISSUE THREAD

**Issue by tvdpid** [MatthewReid854/reliability#40]
Hi,

I think there is an issue with RankAdjustment.
It forgets sorting the data before calculating the Rank Adjustment Estimates.
![RankAdjustment](https://github.com/MatthewReid854/reliability/assets/61689455/889867b1-91e6-4706-9162-85783160b8c3)

Kind regards,
Tom

**Comment by MatthewReid854** [comment]
Fixed in v0.8.12.
Thanks for identifying this.
