### ISSUE TITLE
[BUG] - A minor problem in Reliability_testing.chi2test related to numpy.histogram

### ISSUE THREAD

**Issue by ck52liwei** [MatthewReid854/reliability#41]
**Describe the bug**

A minor problem in 0.8.12

The parameter `normed` in `numpy.histogram` has been [deprecated](https://numpy.org/doc/1.23/reference/generated/numpy.histogram.html) later than 1.23.  So when I run the example code of Chi-squared test, Pycharm raises an "unexpected keyword argument 'normed'" error. Maybe this will happen in newer version of numpy. My version of numpy is 1.25.2 now and 1.24 before. Both wrong.

**To Reproduce**

The code you executed when you found the bug.

```
from reliability.Datasets import mileage
from reliability.Distributions import Normal_Distribution
from reliability.Reliability_testing import chi2test
import numpy as np
import matplotlib.pyplot as plt

data = mileage().failures
dist = Normal_Distribution(mu=30011, sigma=10472)
bins = [0, 13417, 18104, 22791, 27478, 32165, 36852, 41539, 46226, np.inf] #it is not necessary to specify the bins and leaving them unspecified is usually best
chi2test(distribution=dist, data=data, bins=bins)
plt.show()
```

The output that Python gave you.

```
  File "D:\test.py", line 10, in <module>
    chi2test(distribution=dist, data=data, bins=bins)
  File "D:\Program Files\Python39\lib\site-packages\reliability\Reliability_testing.py", line 1016, in __init__
    observed, bin_edges = np.histogram(
TypeError: histogram() got an unexpected keyword argument 'normed'
```

**Expected behavior**

normal result and plot.

**Screenshots**

none.

**Additional context**

none.

**Comment by MatthewReid854** [comment]
Fixed in v0.8.13.
Thanks for identifying this bug.
