### ISSUE TITLE
[BUG] - Stress - Strength Interference Erroneous Result

### ISSUE THREAD

**Issue by ctenold** [MatthewReid854/reliability#43]
**Describe the bug**
Resulting probability of failure is ~0%, need a larger number of trapezoids (x, defined by np.linspace) for the interval to converge on the expected value.
Also, the shading to the right of the salmon region should probably be blue (although I could also see the argument for filling with salmon since there is a high probability of failure in this region...)

**To Reproduce**
```python
from reliability import Distributions
from reliability.Other_functions import stress_strength
import matplotlib.pyplot as plt

mu = 5.07
sigma = 1.68       
stress = Distributions.Lognormal_Distribution(mu=mu, sigma=sigma )

beta = 3
eta = 250
strength = Distributions.Weibull_Distribution(alpha=eta, beta=beta)

stress_strength(stress=stress, strength=strength)
plt.xlim(0,600)
```
Result:
```
Stress - Strength Interference
Stress Distribution: Lognormal Distribution (μ=5.07,σ=1.68)
Strength Distribution: Weibull Distribution (α=250,β=3)
Probability of failure (stress > strength): 3.11692e-06 %
```
![image](https://github.com/MatthewReid854/reliability/assets/88893153/f52eb07a-893b-4ffa-a01b-a7119ef2dcde)

**Expected behavior**
Probability of failure should be ~44%
![image](https://github.com/MatthewReid854/reliability/assets/88893153/894f98d4-5163-4de0-ab16-e969c74080f3)

**Additional context**
In my case, I needed >8K trapezoids to get this to converge. I can come up with other examples where more trapezoids would be needed, but these examples are less and less realistic. I'd propose increasing the number of trapezoids to 100K or 1M to cover 99.9% of use cases without impacting performance.
```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

list=[]
for num_trapz in range(1000,1000000,1000):
    x = np.linspace(
        min(stress.quantile(1e-8), strength.quantile(1e-8)),
        max(strength.quantile(1 - 1e-8), stress.quantile(1 - 1e-8)),
        num_trapz,
    )  # we take the min and max here since there may be cases when stress > strength
    prob_of_failure = np.trapz(
        strength.PDF(x, show_plot=False) * stress.SF(x, show_plot=False), x
    )
    list.append([num_trapz, prob_of_failure])
df_probability = pd.DataFrame(list, columns=['Number of Trapezoids', 'Probability of Failure'])

df_probability.plot(x='Number of Trapezoids', y='Probability of Failure', kind='scatter')

plt.xscale('log')
``` 
![image](https://github.com/MatthewReid854/reliability/assets/88893153/c6a0c2ca-4ad6-434d-bc7f-b998fce278ad)

For the fill, here's another example of how the current method of filling can get mixed up:
```python
from reliability import Distributions
from reliability.Other_functions import stress_strength
import matplotlib.pyplot as plt

beta = 3
eta = 250
stress = Distributions.Weibull_Distribution(alpha=eta, beta=beta, gamma=100)

strength = Distributions.Weibull_Distribution(alpha=eta, beta=beta)

stress_strength_og(stress=stress, strength=strength)
plt.xlim(0,600)
``` 
Stress - Strength fill regions reversed:
![image](https://github.com/MatthewReid854/reliability/assets/88893153/6506c6e4-ebb9-4aff-97fa-5f694693ebf1)

Should be:
![image](https://github.com/MatthewReid854/reliability/assets/88893153/c976f9cb-5717-48f0-9313-b1f189a708b5)

**Comment by MatthewReid854** [comment]
Thanks very much for identifying this and for providing such a thorough analysis and solution. I implemented all of this and also improved some of the xlim defaults for plotting. Changes are live in v0.8.14. Please test them and let me know if there's any issues.

**Comment by ctenold** [comment]
Works great!
