### ISSUE TITLE
Lognormal_Distribution.CDF does not return tuple

### ISSUE THREAD

**Issue by gutandrHSLU** [MatthewReid854/reliability#46]
Hello, I'm new to Bug reporting... let me know if the report is not the way it should be. Cheers!

Description:
Lognormal_distribution.CDF returns:
(array(([1, 2, 3, ...]), (array([1, 2, 3, ...]),), array([1, 2, 3, ...])) but should return
(array(([1, 2, 3, ...]), (array([1, 2, 3, ...]  ), array([1, 2, 3, ...]))
                                                        ^
To Reproduce:
Call Lognormal_distribution.CDF function with CI and CI_x values.

In Distribution.py line 2471
cdf_point = (
   ss.lognorm.cdf(CI_x, self.sigma, self.gamma, np.exp(self.mu)),
)
should be
cdf_point = ss.lognorm.cdf(CI_x, self.sigma, self.gamma, np.exp(self.mu))

(As is the case e.g., in Normal_Distribution.CDF)

**Comment by MatthewReid854** [comment]
Fixed in v0.8.16.
Thanks very much for identifying this issue. Apologies for the time it has taken to fix it.
