### ISSUE TITLE
Extract confidence bounds

### ISSUE THREAD

**Issue by rokopi-byte** [MatthewReid854/reliability#47]
I'm doing the following in MATLAB to extract CI and plot them:

```
[~,pCov] = wbllike([parameters1(1),parameters1(2)],H-sogliaH);
[H_cdf_W, H_cdf_W_ci1,H_cdf_W_ci2] =wblcdf(H0,parameters1(1),parameters1(2),pCov,0.05);
```

I know I can plort CI directly in reliability, but.. how can I extract values and have something like  H_cdf_W_ci1 and H_cdf_W_ci2 ?

**Comment by MatthewReid854** [comment]
The following documentation provides an example of how the values from the confidence bounds can be extracted.
https://reliability.readthedocs.io/en/latest/Working%20with%20fitted%20distributions.html

If you have further questions on how to do things, please send them via email. Github issues are reserved for errors in the code.
